server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://3.110.54.121:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://3.110.54.121:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://3.110.54.121:1003
    cart:
      path: /cart/**
      url: http://3.110.54.121/api/v1
